### ISSUE TITLE
little nursery rhymes for afk channel?

### ISSUE THREAD

**Issue by crazygmr101** [starstruck-bot/StarStruck#19]
basically title. maybe constant?

**Comment by bunny-panda** [comment]
I think you should do it, but I'm only one person sooooo?

**Comment by crazygmr101** [comment]
I mean I know imma do it, i just need input :>

**Comment by missmaddles** [comment]
do it u won’t

**Comment by Naia-love** [comment]
hmmm. good idea tbh

**Comment by crazygmr101** [comment]
separate channel for afk-ing maybe? we'd have to watch for discord sending people to the afk channel

music would still be needed tho

**Comment by crazygmr101** [comment]
separate channel for afk-ing maybe? we'd have to watch for discord sending people to the afk channel

music would still be needed tho
