### ISSUE TITLE
Daycare application

### ISSUE THREAD

**Issue by starstruck-manager** [starstruck-bot/StarStruck#40]
Suggestion by 𝙵𝚊𝚕𝚕𝚎𝚗𝚂𝚊𝚝𝚞𝚛𝚗#7990 (563149062988234761)
I think we should make the daycare a place where littles & CG’s can Roleplay & a place where we can ping for CG’s or Littles!

**Comment by crazygmr101** [comment]
I do believe that applications should be a thing, since this is a place where littles can be .. very little, and we dont just want anyone joining it

**Comment by crazygmr101** [comment]
Think I'm gonna make applications dm'ed to the bot, maybe use !daycare to start, and dm question after question? That'd keep them completely private.
The other alternative would be to maybe make a role, that once someone submits an application, immedately delete the app, send it to a staff channel and lock them out of the application channel.

**Comment by crazygmr101** [comment]
done, finally?
